import { chromium, firefox, webkit } from "playwright";
const origin=process.env.MINDMAKE_ORIGIN||"http://127.0.0.1:4327";const path="/prototypes/website-redesign-recovery/component-selection/navigation-overlay-configurator/index.html";const failures=[];const fail=(condition,message)=>{if(condition)failures.push(message)};
for(const [name,engine] of Object.entries({chromium,firefox,webkit})){
  const browser=await engine.launch({headless:true});
  for(const viewport of [{width:1280,height:900},{width:390,height:844}]){
    const page=await browser.newPage({viewportSize:viewport});const errors=[];page.on("console",m=>{if(m.type()==="error")errors.push(m.text())});page.on("pageerror",e=>errors.push(e.message));
    await page.goto(origin+path,{waitUntil:"networkidle"});await page.evaluate(()=>localStorage.removeItem("mindmake-navigation-overlay-combination-v1"));await page.reload({waitUntil:"networkidle"});const prefix=`${name} ${viewport.width}x${viewport.height}`;
    fail(errors.length>0,`${prefix}: console errors ${errors.join(" | ")}`);fail(await page.locator('input[type="radio"]').count()!==36,`${prefix}: expected 36 radio controls`);const badTargets=await page.locator('.segments span').evaluateAll(nodes=>nodes.filter(node=>node.getBoundingClientRect().height<44).length);fail(badTargets>0,`${prefix}: ${badTargets} targets below 44px`);fail(await page.evaluate(()=>document.documentElement.scrollWidth>document.documentElement.clientWidth+1),`${prefix}: horizontal overflow`);fail(!(await page.locator('img').evaluateAll(nodes=>nodes.every(node=>node.complete&&node.naturalWidth>0))),`${prefix}: logo asset incomplete`);
    const fit=await page.locator('.preview-card').evaluateAll(cards=>cards.map(card=>{const surface=card.querySelector('.menu-surface').getBoundingClientRect();const content=card.querySelector('.menu-surface');return{kind:card.classList.contains('preview-mobile')?'mobile':'desktop',scrollHeight:content.scrollHeight,clientHeight:content.clientHeight,top:surface.top,bottom:surface.bottom}}));for(const item of fit)fail(item.scrollHeight>item.clientHeight+1,`${prefix}: ${item.kind} menu clips ${JSON.stringify(item)}`);
    await page.locator('label:has(input[name="ground"][value="film"])').click();await page.locator('label:has(input[name="structureMobile"][value="grouped"])').click();await page.getByRole('button',{name:'Lock this combination'}).click();fail(!(await page.getByRole('button',{name:'Combination locked'}).isVisible()),`${prefix}: lock state missing`);fail(!(await page.getByText('Overlay ground: film',{exact:false}).isVisible()),`${prefix}: changed readback missing`);await page.reload({waitUntil:'networkidle'});fail(!(await page.getByRole('button',{name:'Combination locked'}).isVisible()),`${prefix}: persistence failed`);fail(!(await page.getByLabel('Film-backed',{exact:true}).isChecked()),`${prefix}: changed selection not restored`);
  }
  await browser.close();
}
console.log(JSON.stringify({failures},null,2));if(failures.length)process.exitCode=1;
