(() => {
  const data={brain:{title:'Your judgement<br />at work.',lede:'Turn your standards, context and past decisions into a system that helps you make the next call.',caption:'The useful part is a system that knows what you would keep, change or reject.',source:'Anonymous client outcome · Research and content',steps:["The founder\'s standards","A system they own","Used on real work"],result:'Research-backed publishing moved from days to under an hour, and from roughly monthly to most days.',film:'../../../../src/assets/films/film-02-loop.mp4'},gtm:{title:'Make the business<br />easier to buy.',lede:'Rebuild one part of how the business reaches customers and gets paid: product, price, positioning or people.',caption:'Start with the commercial decision that is holding the rest of the system back.',source:'Anonymous client outcome · Media advisory',steps:['Expertise people value','A clear offer','A defined plan launched'],result:'A respected advisory firm turned its expertise into a clear offer clients could buy.',film:'../../../../src/assets/films/film-04-loop.mp4'}};
  const form=document.querySelector('#routeForm'),previews=[...document.querySelectorAll('.site-frame')],desktop=previews[0],mobile=previews[1],shell=document.querySelector('.review-shell'),lockButton=document.querySelector('#lockButton'),resetButton=document.querySelector('#resetButton'),output=document.querySelector('#selectionReadout'),storageKey='mindmake-homepage-route-combination-v1',defaults=Object.fromEntries(new FormData(form).entries());
  const labels={compositionDesktop:'Desktop composition',compositionMobile:'Mobile sequence',titleDesktop:'Desktop title scale',titleMobile:'Mobile title scale',measureDesktop:'Desktop title measure',measureMobile:'Mobile title measure',action:'Start-here position',back:'Back control',caption:'Film caption',receipt:'Proof receipt',steps:'Proof steps',reveal:'Reveal behaviour'};
  const read=()=>Object.fromEntries(new FormData(form).entries());
  const apply=state=>{desktop.dataset.compositionDesktop=state.compositionDesktop;desktop.dataset.titleDesktop=state.titleDesktop;desktop.dataset.measureDesktop=state.measureDesktop;mobile.dataset.compositionMobile=state.compositionMobile;mobile.dataset.titleMobile=state.titleMobile;mobile.dataset.measureMobile=state.measureMobile;previews.forEach(p=>{p.dataset.action=state.action;p.dataset.back=state.back;p.dataset.caption=state.caption;p.dataset.receipt=state.receipt;p.dataset.steps=state.steps;p.dataset.reveal=state.reveal;});};
  const showRoute=key=>{const item=data[key];previews.forEach(p=>{p.querySelector('.route-copy h2').innerHTML=item.title;p.querySelector('.lede').textContent=item.lede;p.querySelector('figcaption').textContent=item.caption;p.querySelector('.receipt header p').textContent=item.source;p.querySelectorAll('.receipt li').forEach((li,i)=>li.textContent=item.steps[i]);p.querySelector('blockquote').textContent=item.result;p.querySelector('video source').src=item.film;p.querySelector('video').load();});document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('is-active',b.dataset.route===key));};
  document.querySelectorAll('[data-route]').forEach(button=>button.addEventListener('click',()=>showRoute(button.dataset.route)));
  form.addEventListener('change',()=>{apply(read());shell.classList.remove('is-locked');lockButton.textContent='Lock this combination';});
  lockButton.addEventListener('click',()=>{const state=read();localStorage.setItem(storageKey,JSON.stringify(state));const clean={...state};delete clean.comment;history.replaceState(null,'',`#${new URLSearchParams(clean)}`);output.innerHTML=`<strong>Saved locally</strong><br>${Object.entries(labels).map(([k,l])=>`${l}: ${state[k]}`).join('<br>')}<br>Comment: ${state.comment?.trim()||'none'}`;lockButton.textContent='Combination locked';shell.classList.add('is-locked');});
  resetButton.addEventListener('click',()=>{localStorage.removeItem(storageKey);history.replaceState(null,'',location.pathname+location.search);form.reset();apply(defaults);shell.classList.remove('is-locked');lockButton.textContent='Lock this combination';output.textContent='';});
  let saved=null;try{saved=JSON.parse(localStorage.getItem(storageKey))}catch{saved=null}if(saved){Object.entries(saved).forEach(([name,value])=>{const target=form.elements.namedItem(name);if(target instanceof RadioNodeList)target.value=value;else if(target)target.value=value});apply(read());lockButton.click()}else apply(defaults);showRoute('brain');
})();
